### PR TITLE
patch for gz pack under windows using 7zip

### PR DESCRIPTION
**Pull request by trigaut**

### CODE REVIEW

**Comment by trigaut** [comment]
@MarcMush could you try this fix of the `gz_pack` function with windows ?
You have to install 7Zip if it is not installed and define this environment variable: 
`ENV["7ZPATH"] = PATH_TO_YOUR_7ZIP_INSTALL`

**Comment by MarcMush** [comment]
another solution would be to tell the user to add the 7zip folder to path (in my case `C:\Program Files\7-Zip\`) and simply call `7z`
`gzpack` is now working but tests are not passing

```
EMS simulator's body: Error During Test at C:\Users\Marc\.julia\dev\EMSx\test\runtests.jl:47
  Got exception outside of a @test
  price DataFrame at C:\Users\Marc\.julia\dev\EMSx\test\metadata\edf_prices.csv is not in expected shape
  Stacktrace:
   [1] error(::String) at .\error.jl:33
   [2] load_prices(::String) at C:\Users\Marc\.julia\dev\EMSx\src\database_interface\simulation_interface.jl:39
   [3] top-level scope at C:\Users\Marc\.julia\dev\EMSx\test\runtests.jl:50
   [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Test\src\Test.jl:1113
   [5] top-level scope at C:\Users\Marc\.julia\dev\EMSx\test\runtests.jl:49
   [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Test\src\Test.jl:1113
   [7] top-level scope at C:\Users\Marc\.julia\dev\EMSx\test\runtests.jl:30
   [8] include(::String) at .\client.jl:439
   [9] top-level scope at none:6
   [10] eval(::Module, ::Any) at .\boot.jl:331
   [11] exec_options(::Base.JLOptions) at .\client.jl:264
   [12] _start() at .\client.jl:484

Test Summary:          | Pass  Error  Total
EMSx.jl test set       |    6      1      7
  Preparing data       |    6             6
  EMS simulator's body |           1      1
ERROR: LoadError: Some tests did not pass: 6 passed, 0 failed, 1 errored, 0 broken.
in expression starting at C:\Users\Marc\.julia\dev\EMSx\test\runtests.jl:28
ERROR: Package EMSx errored during testing
```

**Comment by MarcMush** [comment]
it's a change in `DataFrames.jl` https://github.com/JuliaData/DataFrames.jl/pull/2199
`names(::DataFrame)` now returns a `Vector{String}` instead of a `Vector{Symbol}`

I guess we should update to DataFrames v0.21.0

**Review by MarcMush — APPROVED** [review]

**Comment by MarcMush** [comment]
updated instructions for windows users: 7zip installation folder needs to be added to PATH (see readme)

**Pull request merged**
